### ISSUE TITLE
Potential update issues (`updated` hook, `$nextTick`)

### ISSUE THREAD

**Issue by WofWca** [mercs600/vue2-perfect-scrollbar#34]
Shouldn't it call `ps.update()` on the next tick after the `updated` hook has been called?
See what Vue docs say:
https://vuejs.org/v2/api/#updated, ([page source code](https://github.com/vuejs/vuejs.org/blame/3a0b31857aaedf6944efe2649c7d330a21bda247/src/v2/api/index.md#L871-L880))

**Comment by mercs600** [comment]
Ok, right it may cause some issues, did you see some troubles with that ?

**Comment by WofWca** [comment]
I personally did not happen to.

**Comment by mercs600** [comment]
Ok, we can setup if on nextTick ofc

**Comment by Dagdelo** [comment]
I have this issue, I'm trying to implement a infinite scroll, when the event 'ps-y-reach-start' more elements are provided, but the scroll bar jump to the top...

**Comment by mercs600** [comment]
@Dagdelo Are you able to reproduce it on code sandbox ?

**Comment by Dagdelo** [comment]
Yeah. Just give-me some time.

**Comment by Dagdelo** [comment]
https://codesandbox.io/s/vue-perfect-scrollbar-component-local-registration-gdrg4

If we add items on top of the list, the undesirable behavior happens... But when we add on the bottom it acts as expected.

Note: if I don't call update on the PS instance, the scrollbar just updates when the user scrolls; if we add an @ps-y-reach-start they enter in a disgusting loop since when adding on the top the scrolls go to the top instead of preserves his position.

**Comment by mercs600** [comment]
@Dagdelo I edited your codesandbox project and just added local perfect scrollbar component with update method on $nextTick cycle. Just check it is helpful for you ? . https://codesandbox.io/s/vue-perfect-scrollbar-component-local-registration-rhvle?fontsize=14&hidenavigation=1&theme=dark
