### ISSUE TITLE
ps-y-reach-end event triggers before going to another page

### ISSUE THREAD

**Issue by zaharr2** [mercs600/vue2-perfect-scrollbar#46]
I use this event for infinity scroll. But When you go to another page, the event triggers one more time. I can’t figure out how to avoid this.

**Comment by mercs600** [comment]
I can imagine only that is caused because when you load a new page, content in your scrollbar container is loading asynchronously and before content will appear there this event is called. Just check this hypothesis with empty scrollbar container and listen on this event. 

Are you able to reproduce this issue to me on code sandbox ?

**Comment by zaharr2** [comment]
Unfortunately, I do not know how to use the codebox. I'll try to figure it out later.
I’ll describe the problem a little more.
This event is called from a component that is not on the new page. It feels like it's being called before the page is deleted.
For example, I’m going from the purchase page to my account page. The perfect scroll component is on the purchase page and is not on the account page. During the transition from the purchase page to the page of my account, an event ps-y-reach-end is triggered.

**Comment by zaharr2** [comment]
It turns out that the event is called from the previous page immediately before switching to a new one.

**Comment by zaharr2** [comment]
I think I solved the problem. I'm sorry. This was not associated with vue2-perfect-scrollbar. Hold the star =)
